/**
 *  Copyright (c) 2026 khrotu. Apache License 2.0.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import { REMIX_MODULES, COMPILE_REMIX_CSS } from '@/lib/css-templates';
import type { ModuleValue } from '@/stores/useRemixStore';
describe('css-templates', () => {
  describe('REMIX_MODULES', () => {
    it('should define adblock module with correct properties', () => {
      const mod = REMIX_MODULES.adblock;
      expect(mod).toBeDefined();
      expect(mod.name).toBe('AdBlock');
      expect(mod.selector).toContain('.AdBannerContainer');
      expect(mod.selector).toContain('.LoadingOverlayRightAdBannerContainer');
      expect(mod.selector).toContain("[id^='bloxd-io_']");
      expect(mod.baseCss).toContain('display: none !important');
    });
    it('should define logo module with url input', () => {
      const mod = REMIX_MODULES.logo;
      expect(mod).toBeDefined();
      expect(mod.selector).toBe('.TitleContainer');
      expect(mod.baseCss).toContain('background-size: contain');
      expect(mod.baseCss).toContain('background-repeat: no-repeat');
      const urlInput = mod.inputs.find(i => i.key === 'url');
      expect(urlInput).toBeDefined();
      expect(urlInput!.type).toBe('text');
      expect(urlInput!.format).toContain('url(');
    });
    it('should define buttons module with gradient inputs', () => {
      const mod = REMIX_MODULES.buttons;
      expect(mod).toBeDefined();
      expect(mod.selector).toContain('.BlueButton');
      expect(mod.selector).toContain('.NewButton');
      expect(mod.baseCss).toContain('border-radius');
      expect(mod.baseCss).toContain('background-color: transparent');
      expect(mod.inputs.length).toBeGreaterThanOrEqual(3);
      expect(mod.extraSelectors).toBeDefined();
      expect(mod.extraSelectors![0]).toContain('.ButtonTopBorder');
      expect(mod.extraSelectors![0]).toContain('.ButtonBottomBorder');
    });
    it('should define all expected modules', () => {
      const expectedModules = ['adblock', 'crosshair', 'chat', 'health', 'inventory', 'hotbar', 'logo', 'buttons', 'fps'];
      expectedModules.forEach(id => {
        expect(REMIX_MODULES[id]).toBeDefined();
      });
    });
  });
  describe('COMPILE_REMIX_CSS', () => {
    it('should generate adblock CSS with correct selectors', () => {
      const css = COMPILE_REMIX_CSS({ adblock: {} });
      expect(css).toContain('.AdBannerContainer');
      expect(css).toContain('.LoadingOverlayRightAdBannerContainer');
      expect(css).toContain("[id^='bloxd-io_']");
      expect(css).toContain('display: none !important');
    });
    it('should generate logo CSS with provided URL', () => {
      const url = 'https://example.com/logo.svg';
      const css = COMPILE_REMIX_CSS({ logo: { url } });
      expect(css).toContain('.TitleContainer');
      expect(css).toContain(`url('${url}')`);
      expect(css).toContain('background-size: contain');
      expect(css).toContain('background-repeat: no-repeat');
    });
    it('should generate buttons CSS with provided colors and border child rules', () => {
      const css = COMPILE_REMIX_CSS({
        buttons: {
          border: '#0000ff',
          angle: 174,
          start: '#00aaff',
          end: '#000033',
        },
      });
      expect(css).toContain('.NewButton');
      expect(css).toContain('.BlueButton');
      expect(css).toContain('#0000ff');
      expect(css).toContain('!important');
      expect(css).toContain('linear-gradient');
      expect(css).toContain('.ButtonTopBorder');
      expect(css).toContain('.ButtonBottomBorder');
      expect(css).toContain('.ButtonBody');
    });
    it('should handle empty module values', () => {
      const css = COMPILE_REMIX_CSS({ adblock: {} });
      expect(css).toBeDefined();
      expect(css.length).toBeGreaterThan(0);
    });
    it('should handle multiple active modules', () => {
      const css = COMPILE_REMIX_CSS({
        adblock: {},
        logo: { url: 'test.png' },
      });
      expect(css).toContain('.AdBannerContainer');
      expect(css).toContain('.TitleContainer');
      expect(css).toContain("url('test.png')");
    });
    it('should return header comment', () => {
      const css = COMPILE_REMIX_CSS({});
      expect(css).toContain('Generated by BloxdForge Remix Studio');
    });
    it('should ignore unknown module IDs', () => {
      const css = COMPILE_REMIX_CSS({ nonexistent: { foo: 'bar' } } as unknown as Record<string, ModuleValue>);
      expect(css).not.toContain('nonexistent');
    });
  });
});