/**
 *  Copyright (c) 2026 khrotu. Apache License 2.0.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

export default function BloxdForgeVersionsGuide() {
  return (
    <div className="space-y-6 text-gray-300 leading-relaxed">
      <section>
        <p className="mb-4">
          If you&apos;ve stumbled upon videos or posts about BloxdForge (or at least look like it, we&apos;re sort of stuck with this colour scheme now) that look nothing like its current state or have a different name (I&apos;ll talk about that in a bit), you&apos;re not going crazy. And no, it&apos;s not an April Fool&apos;s joke, although it would be very funny if you&apos;re reading this on April 1st, you&apos;re seeing before your eyes the evolution of BloxdForge, the culmination of years of experimentation, building, and growth.
        </p>
        <p className="mb-4">
          This is the story of how we got here.
        </p>
      </section>
      <section>
        <h2 className="text-2xl font-bold text-white mb-4">The Beginning: A Desktop Dream</h2>
        <p className="mb-4">
          BloxdForge started, surprisingly, as a desktop application – a Python program packaged with PyInstaller (or was it Electron? Even I don&apos;t remember…) that you had to download and install on your computer. It was janky, only worked on Windows, and <strong>extremely</strong> ambitious for what it was: a local, static tool that attempted to work with an online game. If you can&apos;t see where I&apos;m going, it doesn&apos;t work that way. The app was never meant to be. However, no matter how rough it was around the edges, it was enough to prove the concept, and it showed us that people wanted tools like this.
        </p>
        <p className="mb-4">
          That version hasn&apos;t been updated since December 2024. Nearly two years later (or whenever you&apos;re reading this), most of its features don&apos;t work anymore: the GitHub repos it relied on are long gone, there are countless bugs, and at some point you <em>really</em> can&apos;t just call every bug a feature, and the design (or the lack of it) was just… bad. The installer is still on GitHub if you&apos;re curious (<a href="https://github.com/KHROTU/Bloxd-Forge/tree/main/Bloxd%20Forge" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">here</a>), but it&apos;s more of a time capsule now than anything else.
        </p>
        <p className="mb-4">
          The desktop app couldn&apos;t keep up. Still, it was the foundation. It taught us what people needed and what was possible. And it was built together, by two people who believed it could be something more.
        </p>
      </section>
      <section>
        <h2 className="text-2xl font-bold text-white mb-4">Moving to the Web</h2>
        <p className="mb-4">
          Let&apos;s be real, the desktop app was never going to reach everyone. You had to download it from GitHub (which, to normal people, just looks like a sketchy website), ignore your antivirus software, albeit rightfully, flagging the file due to it being generated by PyInstaller, and install it, and this was only for those who used Windows. So we moved to the web – version 2 was born on GitHub Pages, powered by jQuery and a lot of hope and optimism. It most certainly wasn&apos;t fancy, I&apos;d even go as far as to say the desktop app had a better UI, but it worked. Anyone with a browser could use it.
        </p>
        <p className="mb-4">
          We built out the essentials: a game launcher that ran in the browser with some QoL features – some of which lived on to the current version, texture pack downloading, an editor where you could edit textures, manage your files, and create skyboxes. We even wired up an AI chat that could answer questions about Bloxd.io, pulling from a knowledge base we&apos;d assembled. And because we needed some way to support the project, we added optional features that could be unlocked by watching ads. Free for everyone, with a little something extra if you wanted it. (And no, if you&apos;re wondering, I&apos;m not adding back any ads or other forms of distractions; I hate ads, period.)
        </p>
        <p className="mb-4">
          Version 2 was scrappy, but it was a real platform. And we built it together, the way we&apos;d built everything up to that point.
        </p>
      </section>
      <section>
        <h2 className="text-2xl font-bold text-white mb-4">Version 3 and New Directions</h2>
        <p className="mb-4">
          After v2 stabilised, version 3 emerged - still on the same tech stack, still GitHub Pages and jQuery, but with a refreshed interface and some nice quality-of-life improvements. The biggest addition was texture pack previews, something people had been asking for (and also to flex my <em>aWeSoMe</em> coding skills :) – no, you don&apos;t get to judge). You could finally see what a pack looked like before downloading it.
        </p>
        <p className="mb-4">
          But v3 was different in another way. It was primarily developed by my co-creator, not as a joint effort like before. We were both busy with studies and work, pulled in different directions, and trying to survive the cruelty that is society. It wasn&apos;t a split, not in any dramatic sense, but it was the start of us realising we might have different ideas about where this project should go.
        </p>
      </section>
      <section>
        <h2 className="text-2xl font-bold text-white mb-4">Starting Fresh: The Current Version</h2>
        <p className="mb-4">
          After v3, I knew I wanted to rebuild everything from scratch. Not because what we&apos;d built was bad - thousands of people have used it just fine - but because I could see what it could become with modern tools. I wanted Next.js for the performance, Vercel for the infrastructure, TypeScript for the safety, and Tailwind for the design flexibility. I wanted server-side rendering, edge functions, and Progressive Web App capabilities. I wanted to build something that felt like a proper application, and most importantly something that <strong>I</strong> wanted to use.
        </p>
        <p className="mb-4">
          And I wanted to call it v1.x.x. Not v4. Call me cringe, but to me, this was a new beginning, a fresh start with a clean slate and a clearer vision. It was my project now, the way I wanted to build it, and no matter how insignificant it may seem, I needed the version number to reflect that.
        </p>
        <p className="mb-4">
          So I rewrote everything. New UI from the ground up. Schematic previews that you could explore. A proper script editor with syntax highlighting. Downloadable community scripts. Comprehensive guides (like this one). A texture studio that was actually pleasant to use. And underneath it all, a tech stack that could grow with the platform instead of holding it back.
        </p>
        <p className="mb-4">
          This is the version you&apos;re using now. It&apos;s not perfect, and it never will be - there&apos;s always something to improve, always a better way to do things - but it&apos;s mine, and it&apos;s the best version of BloxdForge that&apos;s ever existed.
        </p>
      </section>
      <section>
        <h2 className="text-2xl font-bold text-white mb-4">About Version 3</h2>
        <p className="mb-4">
          When I started building the current version, my co-creator continued developing v3 as a separate project. Eventually, they cloned the v3 repository and gave it a new identity, which is why some older promotional content might look confusing or refer to features that don&apos;t exist here.
        </p>
        <p className="mb-4">
          This wasn&apos;t a falling out. We just wanted to build different things, and that&apos;s okay. Sometimes creative partnerships evolve, and people need space to explore their own ideas. The split didn&apos;t affect our personal relationship - we&apos;re still connected, still supportive of each other - but our projects took different paths.
        </p>
        <p className="mb-4">
          If you&apos;re here at <a href="https://bloxdforge.com" className="text-primary hover:underline">bloxdforge.com</a>, you&apos;re on the current platform. This is the one I&apos;m actively developing and maintaining. The rebranded v3 is its own thing now, with its own vision, and I wish them nothing but the best moving forward.
        </p>
      </section>
      <section>
        <h2 className="text-2xl font-bold text-white mb-4">What&apos;s Next</h2>
        <p className="mb-4">
          I&apos;m constantly updating BloxdForge. New features, bug fixes, performance improvements, UI refinements - it&apos;s an ongoing process. The modern tech stack makes it easier to iterate quickly, to experiment with new ideas, to respond to what the community needs.
        </p>
        <p className="mb-4">
          {/*! SIMPLIFIED START */}
          Some of what&apos;s coming: better mobile support, more advanced scripting tools, deeper workshop integration, improved AI assistance, and a lot of polish. There&apos;s a long list, and it grows every time someone suggests something I hadn&apos;t thought of.
          {/*! SIMPLIFIED END */}
        </p>
        <p className="mb-4">
          If you&apos;re using BloxdForge, thank you. Seriously. This project started as a tool I wanted for myself, and it&apos;s grown into something much bigger because people like you found it useful. Every piece of feedback, every bug report, every feature request - it all helps shape what this becomes.
        </p>
        <p className="mb-4">
          This is just the beginning.
        </p>
      </section>
    </div>
  );
}